[package]

name = "linuxdvb"
version = "0.0.1"
authors = ["Ilkka Rauta <ilkka.rauta@gmail.com>"]

build = "codegen/enums/generate-enums.rs"

[dependencies]

libc = "*"
errno = "*"
bitflags = "*"

[build-dependencies]

case = "*"
regex = "0.1.8"
